# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -direct" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded IDEBaseGUI 0.81 [list source [file join $dir IDEBaseGUI.xotcl]]
package ifneeded IDEConfiguration 0.80 [list source [file join $dir IDEConfiguration.xotcl]]
package ifneeded IDECore 0.81 [list source [file join $dir IDECore.xotcl]]
package ifneeded IDEDebug 0.81 [list source [file join $dir IDEDebug.xotcl]]
package ifneeded IDEDocumentation 0.79 [list source [file join $dir IDEDocumentation.xotcl]]
package ifneeded IDEEditor 0.81 [list source [file join $dir IDEEditor.xotcl]]
package ifneeded IDEErrorReporter 0.74 [list source [file join $dir IDEErrorReporter.xotcl]]
package ifneeded IDEFileBrowser 0.75 [list source [file join $dir IDEFileBrowser.xotcl]]
package ifneeded IDEInternationalizationHelper 0.81 [list source [file join $dir IDEInternationalizationHelper.xotcl]]
package ifneeded IDEKitDeployer 0.74 [list source [file join $dir IDEKitDeployer.xotcl]]
package ifneeded IDEPersistence 0.81 [list source [file join $dir IDEPersistence.xotcl]]
package ifneeded IDEPersistenceAdd 0.80 [list source [file join $dir IDEPersistenceAdd.xotcl]]
package ifneeded IDEPersistenceGUI 0.81 [list source [file join $dir IDEPersistenceGUI.xotcl]]
package ifneeded IDEPersistenceTests 0.74 [list source [file join $dir IDEPersistenceTests.xotcl]]
package ifneeded IDERegexpBrowser 0.74 [list source [file join $dir IDERegexpBrowser.xotcl]]
package ifneeded IDERepositoryImporter 0.74 [list source [file join $dir IDERepositoryImporter.xotcl]]
package ifneeded IDESQLBrowser 0.74 [list source [file join $dir IDESQLBrowser.xotcl]]
package ifneeded IDEScriptEditor 0.76 [list source [file join $dir IDEScriptEditor.xotcl]]
package ifneeded IDEStart 0.80 [list source [file join $dir IDEStart.xotcl]]
package ifneeded IDETclParser 0.80 [list source [file join $dir IDETclParser.xotcl]]
package ifneeded IDETestFramework 0.78 [list source [file join $dir IDETestFramework.xotcl]]
package ifneeded IDETests 0.79 [list source [file join $dir IDETests.xotcl]]
package ifneeded IDETkWinInspector 0.74 [list source [file join $dir IDETkWinInspector.xotcl]]
package ifneeded IDEUpdater 0.75 [list source [file join $dir IDEUpdater.xotcl]]
package ifneeded IDEVCInstaller 0.75 [list source [file join $dir IDEVCInstaller.xotcl]]
package ifneeded IDEView 0.81 [list source [file join $dir IDEView.xotcl]]
package ifneeded IDEWikiReaper 0.74 [list source [file join $dir IDEWikiReaper.xotcl]]
package ifneeded SampleComponent 0.2 [list source [file join $dir SampleComponent.xotcl]]
package ifneeded XOTclIDE 0.79 [list source [file join $dir XOTclIDE.xotcl]]
package ifneeded xdobry::access 0.73 [list source [file join $dir xdobry_access.xotcl]]
package ifneeded xdobry::mssql 0.61 [list source [file join $dir xdobry_mssql.xotcl]]
package ifneeded xdobry::mysql 0.75 [list source [file join $dir xdobry_mysql.xotcl]]
package ifneeded xdobry::odbc 0.74 [list source [file join $dir xdobry_odbc.xotcl]]
package ifneeded xdobry::oratcl 0.74 [list source [file join $dir xdobry_oratcl.xotcl]]
package ifneeded xdobry::pgsql 0.74 [list source [file join $dir xdobry_pgsql.xotcl]]
package ifneeded xdobry::sql 0.78 [list source [file join $dir xdobry_sql.xotcl]]
package ifneeded xdobry::sqlDebug 0.35 [list source [file join $dir xdobry_sqlDebug.xotcl]]
package ifneeded xdobry::sqlite 0.76 [list source [file join $dir xdobry_sqlite.xotcl]]
package ifneeded xometakit 0.78 [list source [file join $dir xometakit.xotcl]]
